### ISSUE TITLE
Non-Integer Quantities

### ISSUE THREAD

**Issue by funnylookinhat** [system76/beansbooks#120]
Add the ability to have quantities accurate to within two decimal places ( to easily support 1/4 or 1/2 units ).  Any split-pennies will be always rounded up just as they are for taxes.

- Adjust Sales Order, Customer Invoice, and Purchase Order forms to support the field ( wider input box and adjusted Javascript ).
- Adjust print views for the same forms to support larger quantities.
- Adjust database fields to support DECIMAL(6,2) and ensure validation is updated to match.

**Comment by Elyrith** [comment]
@funnylookinhat -

Where is the already-written code you mentioned? I'd be happy to take a look and try to get this PR done since I only bill hours (by the quarter) so I can't use BeansBooks until this is done! :smile_cat: 

As for your questions, my thoughts are:
* I'd vote for 3 decimal places since 1/8th of an hour is 0.125. For products, normally you'd have one product that you don't break down and if you sell a master case you either have a separate product for the case or you just multiply by the master case size.
* Since decimals for quantity seems like it's mostly for hourly billing rounding up seems like the normal thing to do.

A quick question for you: If I were to try to figure out the database changes, would they now be done similar to [commit 4ca4056](https://github.com/cdp1337/beansbooks/commit/9c859276f7d4f5decb3077c5d9a763aeaf45e055) now, or would it be more like [your link above](https://github.com/system76/beansbooks/blob/master/application/classes/beans/setup/update/v/1/0/1.php#L29-L45)?

**Comment by funnylookinhat** [comment]
Hi @Elyrith -

I think you're right - three decimal places is probably the best place to land in terms of precision.  Anything more and we're going to just make things excessively hairy.

The best example of adding fields to the DB schema is in a file like this one:
https://github.com/system76/beansbooks/blob/master/application/classes/beans/setup/update/v/1/3.php

A couple of other things to consider if you're going to add this:

- The Javascript will need to be updated for Expenses, Sales, and Purchases to support those decimal quantities.  It should disallow typing anything more after three decimal places have been entered.
- All of the _validate function that are called when creating those same forms will need to be updated.  They should throw an Exception if more than three decimal places are found ( as opposed to just rounding up or cutting off the extra digits ).  i.e. BeansBooks has strict input checking.  For customer sales - you can find the main validation function here: https://github.com/system76/beansbooks/blob/master/application/classes/beans/customer.php#L969-L1082
- All appropriate rounding should already be taking place ( i.e. https://github.com/system76/beansbooks/blob/master/application/classes/beans/customer/sale/create.php#L261-L264 ) - but we can do some pretty extensive testing to make sure the math is all set.

If you do want to send a PR - please make sure you send it to the `develop` branch.
